# Generated by Django 2.2.3 on 2019-07-17 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='classBlog',
            new_name='Post',
        ),
    ]
